// Generated by CoffeeScript 1.6.3
(function() {
  var buffer, chunk, chunk_len, handleMessage, header, host, parseMessage, port, room_id, tcp, token;

  host = 'streaming.campfirenow.com';

  port = 80;

  room_id = 552056;

  token = '19843e80477825e5ec04f897aa40ec19315ff80e';

  tcp = new TcpClient(host, port);

  header = '';

  buffer = '';

  chunk = '';

  chunk_len = null;

  handleMessage = function(msg) {
    return console.log(msg);
  };

  parseMessage = function(str) {
    var e, piece, _i, _len, _ref, _results;
    console.info('CHUNK', str);
    _ref = str.split(/\r/);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      piece = _ref[_i];
      if (!/\{/.test(piece)) {
        continue;
      }
      try {
        _results.push(handleMessage(JSON.parse(piece)));
      } catch (_error) {
        e = _error;
        _results.push(console.error("failed to parse JSON: " + piece));
      }
    }
    return _results;
  };

  tcp.addResponseListener(function(str) {
    var left, m;
    buffer += unescape(encodeURIComponent(str));
    while (buffer.length > 0) {
      if (!header) {
        if (!(m = buffer.match(/([\s\S]+?)\r?\n\r?\n([\s\S]*)/))) {
          return;
        }
        header = m[1];
        buffer = m[2];
      }
      if (chunk_len != null) {
        left = chunk_len - chunk.length;
        chunk += buffer.slice(0, left);
        buffer = buffer.slice(left);
        if (chunk.length === chunk_len) {
          buffer = buffer.slice(2);
          chunk_len = null;
          parseMessage(decodeURIComponent(escape(chunk)));
          chunk = '';
        }
      }
      if (m = buffer.match(/^([0-9a-f]+)\r\n([\s\S]*)/)) {
        chunk_len = parseInt(m[1], 16);
        buffer = m[2];
      } else {
        break;
      }
    }
  });

  tcp.connect(function() {
    return tcp.sendMessage("GET /room/" + room_id + "/live.json HTTP/1.1\r\nAuthorization: Basic " + (btoa("" + token + ":x")) + "\r\nHost: " + host + ":" + port + "\r\nAccept: */*\r\n\r\n");
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
